version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb-service
    volumes:
      - ./mongo_data:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth
    networks:
      - webappnetwork
  mysql_db:
    image: mysql:5.7
    restart: always
    container_name: mysqldb-service
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - webappnetwork
volumes:
  mysql_data:
  mongo_data:
networks:
  webappnetwork:
    driver: bridge
